spring:
  application:
    name: member-profile-service
  profiles:
    default: local
  cloud:
    aws:
      region:
        static: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health,info
